name = "hugo-rose"
license = "GPLv2"
licenselink = "https://github.com/chensoul/hugo-rose/blob/master/LICENSE.md"
description = "Hugo Rose is a responsive, clean and content-focused Hugo theme."
homepage = "https://github.com/chensoul/hugo-rose/"
tags = ["blog", "responsive", "light", "multilingual", "customizable", "widgets", "wordpress"]
features = ["blog", "responsive", "multilingual", "widgets", "rss", "disqus", "google analytics", "wordpress"]
min_version = "0.123.8"

[author]
  name = "chensoul"
  homepage = "https://github.com/chensoul"

# If porting an existing theme
[original]
  name = "MH Magazine lite"
  homepage = "https://wordpress.org/themes/mh-magazine-lite/"
  repo = "https://themes.trac.wordpress.org/browser/mh-magazine-lite/2.5.6"
